### ISSUE TITLE
error creating the web proxy specified in the 'system.net/defaultproxy' configuration section

### ISSUE THREAD

**Issue by ronnino** [FelisCatus/switchysharp#1068]
Hello,

After I installed and uninstalled your plugin, I'm not able to use some tools that I used before, getting this error:

"Error creating the web proxy specified in the 'system.net/defaultproxy' configuration section". 

Has your plugin modified anything permanently and not removed it to the original state when uninstalled?

Thank you

**Comment by FelisCatus** [comment]
Hey, what's the exact name of the extension that you have installed? Is it `Proxy Switchy!` or `SwitchySharp`?

This is the issue tracker of `SwitchySharp`. And we promise that we never, ever change your **system** proxy settings. All settings are kept inside Chrome, clean and tidy. Nothing is permanently set -- not even a tiny bit could sneak into your `system.net/defaultproxy`.

It is more likely that a different program is causing the problem. Whether be it `Proxy Switchy!` or other tools, it doesn't matter. I would suggest that you double check your system proxy configurations and unset any unwanted settings. I personally don't use Windows, so that's all that I can say.
